#include "reginfo.h"

RegInfo::RegInfo(QWidget *parent) :
    QWidget(parent)
{
    zrLabel = new QLabel(tr("$zero"));
    atLabel = new QLabel(tr("$at"));
    v0Label = new QLabel(tr("$v0"));
    v1Label = new QLabel(tr("$v1"));
    a0Label = new QLabel(tr("$a0"));
    a1Label = new QLabel(tr("$a1"));
    a2Label = new QLabel(tr("$a2"));
    a3Label = new QLabel(tr("$a3"));
    t0Label = new QLabel(tr("$t0"));
    t1Label = new QLabel(tr("$t1"));
    t2Label = new QLabel(tr("$t2"));
    t3Label = new QLabel(tr("$t3"));
    t4Label = new QLabel(tr("$t4"));
    t5Label = new QLabel(tr("$t5"));
    t6Label = new QLabel(tr("$t6"));
    t7Label = new QLabel(tr("$t7"));
    s0Label = new QLabel(tr("$s0"));
    s1Label = new QLabel(tr("$s1"));
    s2Label = new QLabel(tr("$s2"));
    s3Label = new QLabel(tr("$s3"));
    s4Label = new QLabel(tr("$s4"));
    s5Label = new QLabel(tr("$s5"));
    s6Label = new QLabel(tr("$s6"));
    s7Label = new QLabel(tr("$s7"));
    t8Label = new QLabel(tr("$t8"));
    t9Label = new QLabel(tr("$t9"));
    k0Label = new QLabel(tr("$k0"));
    k1Label = new QLabel(tr("$k1"));
    gpLabel = new QLabel(tr("$gp"));
    spLabel = new QLabel(tr("$sp"));
    fpLabel = new QLabel(tr("$fp"));
    raLabel = new QLabel(tr("$ra"));

    zrLineEdit = new QLineEdit;
    atLineEdit = new QLineEdit;
    v0LineEdit = new QLineEdit;
    v1LineEdit = new QLineEdit;
    a0LineEdit = new QLineEdit;
    a1LineEdit = new QLineEdit;
    a2LineEdit = new QLineEdit;
    a3LineEdit = new QLineEdit;
    t0LineEdit = new QLineEdit;
    t1LineEdit = new QLineEdit;
    t2LineEdit = new QLineEdit;
    t3LineEdit = new QLineEdit;
    t4LineEdit = new QLineEdit;
    t5LineEdit = new QLineEdit;
    t6LineEdit = new QLineEdit;
    t7LineEdit = new QLineEdit;
    s0LineEdit = new QLineEdit;
    s1LineEdit = new QLineEdit;
    s2LineEdit = new QLineEdit;
    s3LineEdit = new QLineEdit;
    s4LineEdit = new QLineEdit;
    s5LineEdit = new QLineEdit;
    s6LineEdit = new QLineEdit;
    s7LineEdit = new QLineEdit;
    t8LineEdit = new QLineEdit;
    t9LineEdit = new QLineEdit;
    k0LineEdit = new QLineEdit;
    k1LineEdit = new QLineEdit;
    gpLineEdit = new QLineEdit;
    spLineEdit = new QLineEdit;
    fpLineEdit = new QLineEdit;
    raLineEdit = new QLineEdit;

    mainLayout = new QGridLayout(this);
    mainLayout->setSpacing(6);

    mainLayout->addWidget(zrLabel, 0, 0, 1, 1);
    mainLayout->addWidget(zrLineEdit, 0, 1, 1, 1);
    mainLayout->addWidget(atLabel, 1, 0, 1, 1);
    mainLayout->addWidget(atLineEdit, 1, 1, 1, 1);
    mainLayout->addWidget(v0Label, 2, 0, 1, 1);
    mainLayout->addWidget(v0LineEdit, 2, 1, 1, 1);
    mainLayout->addWidget(v1Label, 3, 0, 1, 1);
    mainLayout->addWidget(v1LineEdit, 3, 1, 1, 1);
    mainLayout->addWidget(a0Label, 4, 0, 1, 1);
    mainLayout->addWidget(a0LineEdit, 4, 1, 1, 1);
    mainLayout->addWidget(a1Label, 5, 0, 1, 1);
    mainLayout->addWidget(a1LineEdit, 5, 1, 1, 1);
    mainLayout->addWidget(a2Label, 6, 0, 1, 1);
    mainLayout->addWidget(a2LineEdit, 6, 1, 1, 1);
    mainLayout->addWidget(a3Label, 7, 0, 1, 1);
    mainLayout->addWidget(a3LineEdit, 7, 1, 1, 1);
    mainLayout->addWidget(t0Label, 8, 0, 1, 1);
    mainLayout->addWidget(t0LineEdit, 8, 1, 1, 1);
    mainLayout->addWidget(t1Label, 9, 0, 1, 1);
    mainLayout->addWidget(t1LineEdit, 9, 1, 1, 1);
    mainLayout->addWidget(t2Label, 10, 0, 1, 1);
    mainLayout->addWidget(t2LineEdit, 10, 1, 1, 1);
    mainLayout->addWidget(t3Label, 11, 0, 1, 1);
    mainLayout->addWidget(t3LineEdit, 11, 1, 1, 1);
    mainLayout->addWidget(t4Label, 12, 0, 1, 1);
    mainLayout->addWidget(t4LineEdit, 12, 1, 1, 1);
    mainLayout->addWidget(t5Label, 13, 0, 1, 1);
    mainLayout->addWidget(t5LineEdit, 13, 1, 1, 1);
    mainLayout->addWidget(t6Label, 14, 0, 1, 1);
    mainLayout->addWidget(t6LineEdit, 14, 1, 1, 1);
    mainLayout->addWidget(t7Label, 15, 0, 1, 1);
    mainLayout->addWidget(t7LineEdit, 15, 1, 1, 1);
    mainLayout->addWidget(s0Label, 16, 0, 1, 1);
    mainLayout->addWidget(s0LineEdit, 16, 1, 1, 1);
    mainLayout->addWidget(s1Label, 17, 0, 1, 1);
    mainLayout->addWidget(s1LineEdit, 17, 1, 1, 1);
    mainLayout->addWidget(s2Label, 18, 0, 1, 1);
    mainLayout->addWidget(s2LineEdit, 18, 1, 1, 1);
    mainLayout->addWidget(s3Label, 19, 0, 1, 1);
    mainLayout->addWidget(s3LineEdit, 19, 1, 1, 1);
    mainLayout->addWidget(s4Label, 20, 0, 1, 1);
    mainLayout->addWidget(s4LineEdit, 20, 1, 1, 1);
    mainLayout->addWidget(s5Label, 21, 0, 1, 1);
    mainLayout->addWidget(s5LineEdit, 21, 1, 1, 1);
    mainLayout->addWidget(s6Label, 22, 0, 1, 1);
    mainLayout->addWidget(s6LineEdit, 22, 1, 1, 1);
    mainLayout->addWidget(s7Label, 23, 0, 1, 1);
    mainLayout->addWidget(s7LineEdit, 23, 1, 1, 1);
    mainLayout->addWidget(t8Label, 24, 0, 1, 1);
    mainLayout->addWidget(t8LineEdit, 24, 1, 1, 1);
    mainLayout->addWidget(t9Label, 25, 0, 1, 1);
    mainLayout->addWidget(t9LineEdit, 25, 1, 1, 1);
    mainLayout->addWidget(k0Label, 26, 0, 1, 1);
    mainLayout->addWidget(k0LineEdit, 26, 1, 1, 1);
    mainLayout->addWidget(k1Label, 27, 0, 1, 1);
    mainLayout->addWidget(k1LineEdit, 27, 1, 1, 1);
    mainLayout->addWidget(gpLabel, 28, 0, 1, 1);
    mainLayout->addWidget(gpLineEdit, 28, 1, 1, 1);
    mainLayout->addWidget(spLabel, 29, 0, 1, 1);
    mainLayout->addWidget(spLineEdit, 29, 1, 1, 1);
    mainLayout->addWidget(fpLabel, 30, 0, 1, 1);
    mainLayout->addWidget(fpLineEdit, 30, 1, 1, 1);
    mainLayout->addWidget(raLabel, 31, 0, 1, 1);
    mainLayout->addWidget(raLineEdit, 31, 1, 1, 1);
}
